version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: src
    hostname: web
    command: /bin/sh -c "cd /app/ && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn src.wsgi:application --workers 3 --bind unix:/app/src.sock"
    volumes:
      - ./src:/app
    restart: unless-stopped
    container_name: web
    env_file:
      - config/.envfile
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

  nginx:
    hostname: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./config/nginx/cert.pem:/etc/nginx/cert.pem
#      - ./config/nginx/key.pem:/etc/nginx/key.pem
    depends_on:
      - web
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

  db:
    hostname: db
    image: postgres:12-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - config/.envfile
    ports:
      - "5432:5432"
    container_name: db