# Generated by Django 2.2 on 2020-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название поста')),
                ('description', models.TextField(verbose_name='Текст поста')),
            ],
            options={
                'verbose_name': 'Стандартный пост',
                'verbose_name_plural': 'Стандартные посты',
            },
        ),
    ]
